//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_NorthWindUygulama.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mgo_Kisiler
    {
        public int Id { get; set; }
        public string Ad { get; set; }
        public string Soyad { get; set; }
        public Nullable<short> Yas { get; set; }
        public Nullable<decimal> Telefon { get; set; }
        public Nullable<System.DateTime> D_Tarihi { get; set; }
        public string Dili { get; set; }
    }
}
