//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_NorthWindUygulama.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_satısurunu
    {
        public string ProductName { get; set; }
        public string CategoryName { get; set; }
        public Nullable<int> toplam { get; set; }
    }
}
